use_frameworks!

platform :ios, '12.0'

target 'SparkCom_Example' do
  pod 'SparkCom', :path => '../'

  target 'SparkCom_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
